### ISSUE TITLE
You didn't add me to this repo

### ISSUE THREAD

**Issue by SamDingore** [Sahar-S1/aaejs#1]
@Sahar-S1 can you please add me to this repo it's a major issue if I didn't edit the code.

**Comment by Sahar-S1** [comment]
![IMG_20230302_220752](https://user-images.githubusercontent.com/61236477/222493599-ba9f7f90-6798-4e64-b9bb-72eb315ad777.jpg)

I had invited you when we started this but you didn't accepted my invite 🥺

Don't worry, I've invited you again 😅

**Comment by KshitijPotdar** [comment]
https://github.com/Sahar-S1/aaejs/assets/121808995/e46187c5-c622-45b3-8961-4b6fd10e957c

**Comment by Sahar-S1** [comment]
Bruh
